r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://localhost:3306/recipe_tracker
      username: project_user
      password: 'password'
      schema-generate: NONE
      dialect: MYSQL
micronaut:
  router:
    static-resources:
      default:
        enabled: true   #<1>
        mapping: "/**"  #<2>
        paths: "classpath:static" #<3>
logger:
    levels:
#        io.micronaut.context.DefaultBeanContext: OFF
#        io.micronaut.context.lifecycle: OFF
#        io.micronaut.context.env.DefaultEnvironmanet: OFF
#        io.micronaut.context.DefaultBeanContext: OFF
#        io.micronaut.context.lifecycle: OFF
#         io.micronaut.context: ERROR
   #     io.netty.util.internal: ERROR
    #    io.netty.handler.ssl: ERROR
        dev.miku.r2dbc.mysql.MySqlConnection: ERROR